app/urls.py
from django.urls import path
from . import views

app_name = 'app'
urlpatterns = [
    path('', views.WatchListView.as_view(), name='watchlist'),
    path('oi/<str:symbol>/', views.OIView.as_view(), name='oi'),
    path('historical/', views.HistoricalView.as_view(), name='historical'),
]

trade/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

app/models.py
from decimal import Decimal
from django.db import models

class Historical(models.Model):
    name = models.CharField(max_length=256)
    symbol = models.CharField(max_length=128)
    price = models.DecimalField(max_digits=20, decimal_places=3, default=Decimal('0.0'))
    volume = models.DecimalField(max_digits=20, decimal_places=3, default=Decimal('0.0'))
    dominance = models.DecimalField(max_digits=20, decimal_places=3, default=Decimal('0.0'))
    volume_divided_market = models.DecimalField(max_digits=20, decimal_places=3, default=Decimal('0.0'))
    created_at = models.DateTimeField(auto_now_add=True)

home/models.py
from django.db import models

# Create your models here.

app/views.py
from datetime import datetime, date, timedelta
import pytz
from django.shortcuts import render
from django.db.models import Q
from django.views import View
from django.views.generic.list import MultipleObjectTemplateResponseMixin
from app.models import Historical
from app.utils.cg import get_oi
from app.utils.cmc import CMC_CURRENCY_URL, get_watchlist
from app.utils.historical import convert_historical_query

class WatchListView(MultipleObjectTemplateResponseMixin, View):
    template_name = 'main_page.html'

    def get(self, request):
        search = request.GET.get('search', False)
        vol_change_min = request.GET.get('vol_change_min', default=None)
        dom_min = request.GET.get('dom_min', default=None)
        vol_per_mcap_min = request.GET.get('vol_per_mcap_min', default=None)
        market_cap_min = request.GET.get('market_cap_min', default=None)
        page = request.GET.get('page', default=1)
        page_size = int(request.GET.get('page_size', default=100))
        count, watchlist = get_watchlist(search, vol_change_min, dom_min, vol_per_mcap_min, page, page_size, market_cap_min)
        ctx = { 
            'watchlist': watchlist, 
            'search': search,
            'vol_change_min': vol_change_min,
            'dom_min': dom_min,
            'vol_per_mcap_min': vol_per_mcap_min,
            'page': page,
            'page_size': page_size,
            'num_of_pages': int(count / page_size) + 1,
            'cmc_url': CMC_CURRENCY_URL,
            "market_cap_min": market_cap_min
            }
        return render(request, self.template_name, ctx)

class OIView(MultipleObjectTemplateResponseMixin, View):
    template_name = 'oi_page.html'

    def get(self, request, symbol):
        oi_data = get_oi(symbol)
        ctx = {
            'oi_data': oi_data,
            'symbol': symbol,
        }
        return render(request, self.template_name, ctx)

class HistoricalView(MultipleObjectTemplateResponseMixin, View):
    template_name = 'historical_page.html'

    def get(self, request):
        search = request.GET.get('search')
        start_date_str = request.GET.get('start_date') 
        end_date_str = request.GET.get('end_date')
        price = request.GET.get('price', default=None)
        volume = request.GET.get('volume', default=None)
        dominance = request.GET.get('dominance', default=None)
        volume_divided_market = request.GET.get('volume_divided_market', default=None)

        tz = pytz.timezone('UTC')
        yesterday = datetime.combine(date.today() - timedelta(days=1), datetime.min.time())
        today = datetime.combine(date.today(), datetime.min.time())

        start_date = datetime.strptime(start_date_str, '%Y-%m-%d') if start_date_str else yesterday
        end_date = datetime.strptime(end_date_str, '%Y-%m-%d') if end_date_str else today

        start_date = tz.localize(start_date)
        end_date = tz.localize(end_date)
        if start_date and end_date and search:
            query = Historical.objects.filter(Q(created_at__date=start_date) | Q(created_at__date=end_date), name__icontains=search)
        elif start_date and end_date and not search:
            query = Historical.objects.filter(Q(created_at__date=start_date) | Q(created_at__date=end_date))

        historical_list = convert_historical_query(list(query), price, volume, dominance, volume_divided_market)
        ctx = {
            'search': search,
            'start_date': start_date,
            'end_date': end_date,
            'historical_list': historical_list,
            'price': price,
            'volume': volume,
            'dominance': dominance,
            "volume_divided_market": volume_divided_market,
            'cmc_url': CMC_CURRENCY_URL
        }
        return render(request, self.template_name, ctx)

home/views.py
from django.shortcuts import render

# Create your views here.

app/templates/historical_page.html
{% extends 'base_bootstrap.html' %}
{% block content %}
<h1>Watch list - Historical</h1>
{% if user.is_authenticated %}
    <a href="{% url 'app:watchlist' %}">Watchlist</a>
    <form style="margin-top: 1rem;">
        <input type="text" placeholder="Search.." name="search"
        {% if search %} value="{{ search }}" {% endif %}
        >
        
        <button type="submit">Apply</button>
        <div style="margin-top: 1rem;">
            <label for="start_date">Start date:</label>
            <input style="margin-right: 1rem;" type="date" name="start_date" id="start_date" value="{{ start_date|date:'Y-m-d' }}">
            
            <label for="end_date">End date:</label>
            <input type="date" name="end_date" id="end_date" value="{{ end_date|date:'Y-m-d' }}">
        </div>
        <div class="filter">
          <div style="margin-top: 1rem;">
            <label for="price">Price:</label>
            <input type="number" style="margin-right: 1rem;" id="price" name="price"
            {% if price %} value="{{price}}" {% endif %}>
          </div>
          <div style="margin-top: 1rem;">
            <label for="volume">Volume:</label>
            <input type="number" style="margin-right: 1rem;" id="volume" name="volume"
            {% if volume %} value="{{volume}}" {% endif %}>
          </div>
          <div style="margin-top: 1rem;">
            <label for="dominance">Dominance:</label>
            <input type="number" style="margin-right: 1rem;" id="dominance" name="dominance"
            {% if dominance %} value="{{dominance}}" {% endif %}>
          </div>
          <div style="margin-top: 1rem;">
            <label for="volume_divided_market">Volume / Market cap:</label>
            <input type="number" id="volume_divided_market" name="volume_divided_market"
            {% if volume_divided_market %} value="{{volume_divided_market}}" {% endif %}>
          </div>
      </div>
      </form>
      {% if historical_list %}
      <ul style="margin-top: 1rem">
        {% for item in historical_list %}
        <div>
          {% for key, value in item.items %}
          {% if key != 'slug' %}
          <li>
            <p>{{ key }}: <strong>{% if key == 'Name' %}<a href="{{ cmc_url }}/{{ item.slug }}" target="_blank">{{ value }}</a> {% else %}{{ value }}{% endif %}</strong></p>
          </li>
          {% endif %}
          {% endfor %}
        </div>
        <hr>
        {% endfor %}
      </ul>
      {% endif %}
{% endif %}
{% endblock %}

app/templates/main_page.html
{% extends "base_bootstrap.html" %}
{% block content %}
<h1>Watch list</h1>
<div>
  {% if user.is_authenticated %}

    <a style="margin-right: 1rem" href="{% url 'logout' %}?next={% url 'app:watchlist' %}">Logout</a>
    <a href="{% url 'app:historical' %}">Historical</a>


  <form style="margin-top: 1rem;">
    <input type="text" placeholder="Search.." name="search"
    {% if search %} value="{{ search }}" {% endif %}
    >
    
    <button type="submit">Apply</button>
    <a href="{% url 'app:watchlist' %}"><i class="fa fa-undo"></i></a>
  
    <div style="margin-top: 1rem;">
      <label for="page">Page:</label>
      <input type="number" id="page" name="page" min="1" max="{{ num_of_pages }}"
      {% if page %} value="{{page}}" {% endif %}>
      
      <label for="page_size">Page size:</label>
      <input type="number" id="page_size" name="page_size" min="100" max="5000"
      {% if page_size %} value="{{page_size}}" {% endif %}>
    </div>

    <div style="margin-top: 1rem;">
      <label for="vol_change_min">Volume 24h change min:</label>
      <input type="number" id="vol_change_min" name="vol_change_min"
      {% if vol_change_min %} value="{{vol_change_min}}" {% endif %}>
    </div>

    <div style="margin-top: 1rem;">
      <label for="dom_min">Market cap dominance min:</label>
      <input type="number" step="0.01" id="dom_min" name="dom_min"
      {% if dom_min %} value="{{ dom_min }}" {% endif %}>
    </div>

    <div style="margin-top: 1rem;">
      <label for="vol_per_mcap_min">Volume 24h / Market cap:</label>
      <input type="number" step="0.001" id="vol_per_mcap_min" name="vol_per_mcap_min"
      {% if vol_per_mcap_min %} value="{{vol_per_mcap_min}}" {% endif %}>
    </div>
    <div style="margin-top: 1rem;">
      <label for="market_cap_min">Market cap:</label>
      <input type="number" step="0.001" id="market_cap_min" name="market_cap_min"
      {% if market_cap_min %} value="{{market_cap_min}}" {% endif %}>
    </div>
  </form>
  <p>
  {% if watchlist %}
  <ul>
    {% for item in watchlist %}
    <div style="display: flex">
      <div>
        {% for key, value in item.items %}
        {% if key != 'slug' %}
        <li>
          <p>{{ key }}: 
            <strong>
              {% if key == 'Name' %}<a href="{{ cmc_url }}/{{ item.slug }}" target="_blank">{{ value }}</a>
              {% else %}{% if key == 'Symbol'%}
                {{ value }}
              {% else %}
                {{ value|floatformat:"2g" }}
              {% endif %}
              {% endif %}
            </strong>
          </p>
        </li>
        {% endif %}
        {% endfor %}
      </div>
      <div>
        <a href="{% url 'app:oi' item.Symbol %}" target="_blank">Show OI</a>
      </div>
    </div>
    <hr>
    {% endfor %}
  </ul>
  {% else %}
    <p>No data!</p>
  {% endif %}
  </p>
  {% else %}
  <a href="{% url 'login' %}?next={% url 'app:watchlist' %}">Login</a>
  {% endif %}
</div>
{% endblock %}

app/templates/oi_page.html
{% extends 'base_bootstrap.html' %}
{% block content %}
{% if user.is_authenticated %}
<h1><strong>{{symbol}}</strong> OI</h1>
<div>
    <p>
    {% if oi_data %}
    {% for key, value in oi_data.items %}
        <div>
            <p>{{ key }}: <strong>{{ value }}</strong></p>
        </div>
    {% endfor %}
    {% else %}
      <p>No data!</p>
    {% endif %}
    </p>
    {% else %}
    <a href="{% url 'login' %}?next={% url 'app:watchlist' %}">Login</a>
  </div>
{% endif %}
{% endblock %}

home/templates/base_bootstrap.html
<!DOCTYPE html>
<html>
<head>
<title>{% block title %}{{ settings.APP_NAME }}{% endblock %}</title>
<meta
name="viewport"
content="width=device-width, initial-scale=1, shrink-to-fit=no"
/>
<link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css"
    crossorigin="anonymous">

<link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap-theme.min.css"
    crossorigin="anonymous">

<link rel="stylesheet"
    href="https://code.jquery.com/ui/1.12.1/themes/ui-lightness/jquery-ui.css"
     crossorigin="anonymous">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"
    crossorigin="anonymous"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"
    crossorigin="anonymous"></script>

<script
  src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"
  crossorigin="anonymous"></script>

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/v4-shims.css">

{% block head %} {% endblock %}

</head>
<style>
    #scroll-to-top {
        display: none;
        position: fixed;
        bottom: 20px;
        right: 20px;
        z-index: 99;
        font-size: 16px;
        border: none;
        outline: none;
        background-color: #ddd;
        color: white;
        cursor: pointer;
        padding: 15px;
        border-radius: 10px;
      }
      
      #scroll-to-top:hover {
        background-color: #ccc;
      }
      .filter {
        display: flex;
      }

      /* For large screens (e.g. desktops) */
      @media screen and (min-width: 768px) {
        .filter {
          flex-direction: row;
        }
      }

      /* For small screens (e.g. mobile devices) */
      @media screen and (max-width: 767px) {
        .filter {
          flex-direction: column;
        }
      }
</style>
<body>
<div class="container">
{% block welcome %} {% endblock %}
{% block content%} {% endblock %}
</div>
<button id="scroll-to-top">🔝</button>
{% block footer %} {% endblock %}
</body>
<script>
    const scrollToTopButton = document.getElementById('scroll-to-top');

    // Show the button when the page is scrolled down
    window.addEventListener('scroll', function() {
      if (window.pageYOffset > 100) {
        scrollToTopButton.style.display = 'block';
      } else {
        scrollToTopButton.style.display = 'none';
      }
    });

    // Scroll to the top of the page when the button is clicked
    scrollToTopButton.addEventListener('click', function() {
      window.scrollTo({ top: 0, behavior: 'smooth' });
    });

</script>
</html>